  name: build and deploy spring-api
  on:
    push:
      branches:
        - main

  jobs:
    build-deploy:
      name: build and deploy spring-api
      runs-on: ubuntu-20.04
      steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: setup jdk 17
          uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: 17

        - name: unit tests
          run: mvn -B test --file pom.xml
          
         
        - name: build the app
          run: |
            mvn clean
            mvn -B package --file pom.xml

  name: SonarQube Scan
  jobs:
    sonarqube:
      name: SonarQube Trigger
      runs-on: ubuntu-latest
      steps:
      - name: Checking out
        uses: actions/checkout@master
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
            projectBaseDir: "src/"
            projectKey: "my-custom-project"